server:
    port: 8081

spring:
    application:
        name: nacos-provider-demo
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.129.129:8849 # Nacos服务端地址和端口
                service: ${spring.application.name} # Nacos服务名，默认就是spring.application.name，可以不配置
                group: DEFAULT_GROUP # 服务分组，默认为DEFAULT_GROUP
                weight: 1 # 服务的权重，取值为1-100，数值越大权重越大
                namespace: cbf32534-52a8-4858-88f1-7966ef1178d4 # 命名空间，用来进行服务分隔（在nacos页面创建，复制过来的id）
                cluster-name: DEFAULT #Nacos集群名称
management:
    endpoint:
        web:
            exposure:
                include: "*"
