server:
    port: 8030
spring:
    application:
        name: nacos-sentinel-demo
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.129.129:8849
                service: ${spring.application.name} # Nacos服务名，默认就是spring.application.name，可以不配置
                group: DEFAULT_GROUP # 服务分组，默认为DEFAULT_GROUP
                weight: 1 # 服务的权重，取值为1-100，数值越大权重越大
                namespace: cbf32534-52a8-4858-88f1-7966ef1178d4 # 命名空间，用来进行服务分隔
                cluster-name: DEFAULT #Nacos集群名称
                username: nacos
                password: nacos
        sentinel:
        transport:
            dashboard: 192.168.129.129:8858
feign:
  sentinel:
      # openfeign整合sentinel
      enabled: true



